Repository Al-ways/Al-ways-BE, pull requests merged in 2023-09, with the labels that each got.

#2 [FEAT] Spring Security 설정 (#1)
  build.gradle
Labels: 🍃백엔드

#6 [FEAT]초기 엔티티 설정과 더미데이터 세팅 #5
  src/main/java/com/project/always/domain/BaseEntity.java
  src/main/java/com/project/always/domain/bar/Bar.java
  src/main/java/com/project/always/domain/bar/BarRepository.java
  src/main/java/com/project/always/domain/member/Member.java
  src/main/java/com/project/always/domain/member/MemberRepository.java
  src/main/java/com/project/always/domain/member/ProfileUrl.java
  src/main/java/com/project/always/domain/surbey/Survey.java
  src/main/java/com/project/always/domain/surbey/SurveyRepository.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/test/java/com/project/always/domain/member/MemberRepositoryTest.java
Labels: 🍃백엔드, 🌈기능, ♻️테스트

#11 [FEAT] Swagger, RestDocs 세팅 (#10)
  build.gradle
  src/main/java/com/project/always/controller/api/SampleControllerApi.java
  src/main/java/com/project/always/controller/api/request/SampleRequest.java
  src/main/java/com/project/always/controller/api/response/SampleResponse.java
  src/test/java/com/project/always/controller/api/BaseControllerTest.java
  src/test/java/com/project/always/controller/api/SampleControllerApiTest.java
Labels: 🍃백엔드, 🌈기능, ♻️테스트

#13 [FEAT] 네이버 로그인 기능 구현 (#3)
  .gitignore
  build.gradle
  src/main/java/com/project/always/bar/domain/Bar.java
  src/main/java/com/project/always/bar/domain/BarRepository.java
  src/main/java/com/project/always/domain/member/Member.java
  src/main/java/com/project/always/domain/member/MemberRepository.java
  src/main/java/com/project/always/security/oauth/config/WebConfigure.java
  src/main/java/com/project/always/security/oauth/config/WebSecurityConfigure.java
  src/main/java/com/project/always/security/oauth/dto/UserResponseDto.java
  src/main/java/com/project/always/security/oauth/entity/ProfileUrl.java
  src/main/java/com/project/always/security/oauth/entity/User.java
  src/main/java/com/project/always/security/oauth/enums/AuthProvider.java
  src/main/java/com/project/always/security/oauth/enums/Role.java
  src/main/java/com/project/always/security/oauth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/project/always/security/oauth/jwt/JwtTokenProvider.java
  src/main/java/com/project/always/security/oauth/lib/CookieUtils.java
  src/main/java/com/project/always/security/oauth/oauth2/GoogleOAuth2User.java
  src/main/java/com/project/always/security/oauth/oauth2/KakaoOAuth2User.java
  src/main/java/com/project/always/security/oauth/oauth2/NaverOAuth2User.java
  src/main/java/com/project/always/security/oauth/oauth2/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/project/always/security/oauth/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/project/always/security/oauth/oauth2/OAuth2UserInfo.java
  src/main/java/com/project/always/security/oauth/oauth2/OAuth2UserInfoFactory.java
  src/main/java/com/project/always/security/oauth/oauth2/UserPrincipal.java
  src/main/java/com/project/always/security/oauth/repository/CookieAuthorizationRequestRepository.java
  src/main/java/com/project/always/security/oauth/repository/UserRepository.java
  src/main/java/com/project/always/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/project/always/survey/Survey.java
  src/main/java/com/project/always/survey/SurveyRepository.java
  src/main/java/com/project/always/utils/BaseEntity.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/test/java/com/project/always/domain/member/MemberRepositoryTest.java
Labels: 🍃백엔드, 🌈기능

#12 [FEAT] Kakao 소셜 로그인을 구현한다. (#7)
  src/main/java/com/project/always/bar/Bar.java
  src/main/java/com/project/always/bar/domain/Bar.java
  src/main/java/com/project/always/bar/domain/BarRepository.java
  src/main/java/com/project/always/security/oauth/config/WebConfigure.java
  src/main/java/com/project/always/security/oauth/config/WebSecurityConfigure.java
  src/main/java/com/project/always/security/oauth/controller/OauthControllerApi.java
  src/main/java/com/project/always/security/oauth/dto/UserResponseDto.java
  src/main/java/com/project/always/security/oauth/oauth2/KakaoOauth2User.java
  src/main/java/com/project/always/security/oauth/oauth2/OauthUserInfoFactory.java
  src/main/java/com/project/always/security/oauth/service/CustomOauth2UserService.java
  src/main/java/com/project/always/survey/Survey.java
  src/main/java/com/project/always/survey/SurveyRepository.java
  src/main/java/com/project/always/survey/domain/Survey.java
  src/main/java/com/project/always/survey/domain/SurveyRepository.java
  src/test/java/com/project/always/AcceptanceTest.java
  src/test/java/com/project/always/domain/member/UserRepositoryTest.java
Labels: 🍃백엔드, 🌈기능, 🔨리팩터링

#16 [FIX] OAuth패키지 중복된 클래스 삭제 및 네이밍 수정 (#15)
  src/main/java/com/project/always/bar/Bar.java
  src/main/java/com/project/always/bar/domain/Bar.java
  src/main/java/com/project/always/security/oauth/config/WebSecurityConfigure.java
  src/main/java/com/project/always/security/oauth/oauth2/KakaoOAuth2User.java
  src/main/java/com/project/always/security/oauth/oauth2/KakaoOauth2User.java
  src/main/java/com/project/always/security/oauth/oauth2/OauthUserInfoFactory.java
  src/main/java/com/project/always/security/oauth/service/CustomOauth2UserService.java
  src/main/java/com/project/always/survey/Survey.java
  src/main/java/com/project/always/survey/SurveyRepository.java
  src/main/java/com/project/always/survey/domain/Survey.java
  src/main/java/com/project/always/survey/domain/SurveyRepository.java
Labels: 🐞 버그, 🍃백엔드
